export enum TipoEvento {
  CRIACAO_TRANSPORTE = 'CRIACAO_TRANSPORTE',
  INICIO_SEPARACAO = 'INICIO_SEPARACAO',
  TERMINO_SEPARACAO = 'TERMINO_SEPARACAO',
  INICIO_CONFERENCIA = 'INICIO_CONFERENCIA',
  TERMINO_CONFERENCIA = 'TERMINO_CONFERENCIA',
  INICIO_CARREGAMENTO = 'INICIO_CARREGAMENTO',
  TERMINO_CARREGAMENTO = 'TERMINO_CARREGAMENTO',
  CORTE_PRODUTO = 'CORTE_PRODUTO',
  FATURADO = 'FATURADO',
  LIBERADO_PORTARIA = 'LIBERADO_PORTARIA',
}
